const colors = require('tailwindcss/colors')

module.exports = {
  purge: {
      content: [
          './app/Filament/**/*.php',
          './resources/views/**/*.blade.php',
          './resources/views/filament/**/*.blade.php',
          './vendor/filament/**/*.blade.php',
      ]
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
        colors: {
            lightjudo: {
                '50':  '#fafbf7',
                '100': '#f6fae3',
                '200': '#e9f5aa',
                '300': '#d3ea64',
                '400': '#97d524',
                '500': '#56bc0b',
                '600': '#399d06',
                '700': '#317c09',
                '800': '#285c0d',
                '900': '#1f470e',
            },
            judo: {
                '50': '#A4EAA5',
                '100': '#8FE591',
                '200': '#66DB68',
                '300': '#3DD13F',
                '400': '#2AB22B',
                '500': '#019903',
                '600': '#0A850C',
                '700': '#065507',
                '800': '#032603',
                '900': '#000000',
            },
            amber: colors.amber,
            custom: {
                50: 'rgba(var(--c-50), <alpha-value>)',
                100: 'rgba(var(--c-100), <alpha-value>)',
                200: 'rgba(var(--c-200), <alpha-value>)',
                300: 'rgba(var(--c-300), <alpha-value>)',
                400: 'rgba(var(--c-400), <alpha-value>)',
                500: 'rgba(var(--c-500), <alpha-value>)',
                600: 'rgba(var(--c-600), <alpha-value>)',
                700: 'rgba(var(--c-700), <alpha-value>)',
                800: 'rgba(var(--c-800), <alpha-value>)',
                900: 'rgba(var(--c-900), <alpha-value>)',
                950: 'rgba(var(--c-950), <alpha-value>)',
            },
            danger: {
                50: 'rgba(var(--danger-50), <alpha-value>)',
                100: 'rgba(var(--danger-100), <alpha-value>)',
                200: 'rgba(var(--danger-200), <alpha-value>)',
                300: 'rgba(var(--danger-300), <alpha-value>)',
                400: 'rgba(var(--danger-400), <alpha-value>)',
                500: 'rgba(var(--danger-500), <alpha-value>)',
                600: 'rgba(var(--danger-600), <alpha-value>)',
                700: 'rgba(var(--danger-700), <alpha-value>)',
                800: 'rgba(var(--danger-800), <alpha-value>)',
                900: 'rgba(var(--danger-900), <alpha-value>)',
                950: 'rgba(var(--danger-950), <alpha-value>)',
            },
            gray: {
                50: 'rgba(var(--gray-50), <alpha-value>)',
                100: 'rgba(var(--gray-100), <alpha-value>)',
                200: 'rgba(var(--gray-200), <alpha-value>)',
                300: 'rgba(var(--gray-300), <alpha-value>)',
                400: 'rgba(var(--gray-400), <alpha-value>)',
                500: 'rgba(var(--gray-500), <alpha-value>)',
                600: 'rgba(var(--gray-600), <alpha-value>)',
                700: 'rgba(var(--gray-700), <alpha-value>)',
                800: 'rgba(var(--gray-800), <alpha-value>)',
                900: 'rgba(var(--gray-900), <alpha-value>)',
                950: 'rgba(var(--gray-950), <alpha-value>)',
            },
            info: {
                50: 'rgba(var(--info-50), <alpha-value>)',
                100: 'rgba(var(--info-100), <alpha-value>)',
                200: 'rgba(var(--info-200), <alpha-value>)',
                300: 'rgba(var(--info-300), <alpha-value>)',
                400: 'rgba(var(--info-400), <alpha-value>)',
                500: 'rgba(var(--info-500), <alpha-value>)',
                600: 'rgba(var(--info-600), <alpha-value>)',
                700: 'rgba(var(--info-700), <alpha-value>)',
                800: 'rgba(var(--info-800), <alpha-value>)',
                900: 'rgba(var(--info-900), <alpha-value>)',
                950: 'rgba(var(--info-950), <alpha-value>)',
            },
            primary: {
                50: 'rgba(var(--primary-50), <alpha-value>)',
                100: 'rgba(var(--primary-100), <alpha-value>)',
                200: 'rgba(var(--primary-200), <alpha-value>)',
                300: 'rgba(var(--primary-300), <alpha-value>)',
                400: 'rgba(var(--primary-400), <alpha-value>)',
                500: 'rgba(var(--primary-500), <alpha-value>)',
                600: 'rgba(var(--primary-600), <alpha-value>)',
                700: 'rgba(var(--primary-700), <alpha-value>)',
                800: 'rgba(var(--primary-800), <alpha-value>)',
                900: 'rgba(var(--primary-900), <alpha-value>)',
                950: 'rgba(var(--primary-950), <alpha-value>)',
            },
            success: {
                50: 'rgba(var(--success-50), <alpha-value>)',
                100: 'rgba(var(--success-100), <alpha-value>)',
                200: 'rgba(var(--success-200), <alpha-value>)',
                300: 'rgba(var(--success-300), <alpha-value>)',
                400: 'rgba(var(--success-400), <alpha-value>)',
                500: 'rgba(var(--success-500), <alpha-value>)',
                600: 'rgba(var(--success-600), <alpha-value>)',
                700: 'rgba(var(--success-700), <alpha-value>)',
                800: 'rgba(var(--success-800), <alpha-value>)',
                900: 'rgba(var(--success-900), <alpha-value>)',
                950: 'rgba(var(--success-950), <alpha-value>)',
            },
            warning: {
                50: 'rgba(var(--warning-50), <alpha-value>)',
                100: 'rgba(var(--warning-100), <alpha-value>)',
                200: 'rgba(var(--warning-200), <alpha-value>)',
                300: 'rgba(var(--warning-300), <alpha-value>)',
                400: 'rgba(var(--warning-400), <alpha-value>)',
                500: 'rgba(var(--warning-500), <alpha-value>)',
                600: 'rgba(var(--warning-600), <alpha-value>)',
                700: 'rgba(var(--warning-700), <alpha-value>)',
                800: 'rgba(var(--warning-800), <alpha-value>)',
                900: 'rgba(var(--warning-900), <alpha-value>)',
                950: 'rgba(var(--warning-950), <alpha-value>)',
            },
        }
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
      require('@tailwindcss/typography'),
  ],
}
